const ACTIONS_PREFIX = 'login.actions::';
export const LOGIN = `${ACTIONS_PREFIX}LOGIN`;
export const LOGIN_ERROR = `${ACTIONS_PREFIX}LOGIN_ERROR`;
export const LOGIN_SUCCESS = `${ACTIONS_PREFIX}LOGIN_SUCCESS`;
export const CLEAR_ERROR = `${ACTIONS_PREFIX}CLEAR_ERROR`;
