const ACTIONS_PREFIX = 'register.actions::';

export const ADD_USER_NAME = `${ACTIONS_PREFIX}ADD_USER_NAME`;
export const ADD_USER_LASTNAME = `${ACTIONS_PREFIX}ADD_USER_LASTNAME`;
export const ADD_USER_SEX = `${ACTIONS_PREFIX}ADD_USER_SEX`;
export const ADD_USER_EMAIL = `${ACTIONS_PREFIX}ADD_USER_EMAIL`;
export const ADD_USER_PASSWORD = `${ACTIONS_PREFIX}ADD_USER_PASSWORD`;
export const ADD_USER_PHONENUMBER = `${ACTIONS_PREFIX}ADD_USER_PHONENUMBER`;
export const ADD_USER_BIRTHDATE = `${ACTIONS_PREFIX}ADD_USER_BIRTHDATE`;
