const ACTIONS_PREFIX = 'register.actions::';

export const ADD_USER_INFO = `${ACTIONS_PREFIX}ADD_USER_INFO`;
export const REGISTER_USER = `${ACTIONS_PREFIX}REGISTER_USER`;
export const REGISTER_USER_COMPLETE = `${ACTIONS_PREFIX}REGISTER_USER_COMPLETE`;
